package gt.edu.umg.ingenieria.sistemas.system_graph_figures_and_calculate.view;


import gt.edu.umg.ingenieria.sistemas.system_graph_figures_and_calculate.service.FiguraCuadradoService;
import gt.edu.umg.ingenieria.sistemas.system_graph_figures_and_calculate.service.FiguraCirculoService;
import gt.edu.umg.ingenieria.sistemas.system_graph_figures_and_calculate.service.FiguraRectanguloService;
import gt.edu.umg.ingenieria.sistemas.system_graph_figures_and_calculate.service.FiguraTrianguloService;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yunyor-PC
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
     String figura;
     String colorfigura;
     String colorborde;
     String formato;
    public NewJFrame() {
        initComponents();
        txt_cuadrado.setVisible(false);
        lbl_triangulo.setVisible(false);
        txt_triangulo.setVisible(false);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fig = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_triangulo = new javax.swing.JLabel();
        lbl_cuadrado = new javax.swing.JLabel();
        txt_triangulo = new javax.swing.JTextField();
        txt_cuadrado = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        colorfig = new javax.swing.JComboBox<>();
        bordefig = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuadrado", "Circulo", "Triangulo", "Rectangulo" }));
        fig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                figActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione la figura");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_triangulo.setBackground(new java.awt.Color(0, 204, 204));
        lbl_triangulo.setText("Ingrese la altura");

        lbl_cuadrado.setBackground(new java.awt.Color(51, 255, 0));

        txt_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_trianguloActionPerformed(evt);
            }
        });

        txt_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cuadradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_triangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(lbl_cuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

        jLabel3.setText("Perimetro");

        jLabel4.setText("Area");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gt/edu/umg/ingenieria/sistemas/system_graph_figures_and_calculate/view/edit.png"))); // NOI18N
        jButton1.setText("Dibujar Figura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(310, 220));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gt/edu/umg/ingenieria/sistemas/system_graph_figures_and_calculate/view/edit_add.png"))); // NOI18N
        jButton2.setText("Crear Imagen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        colorfig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro", "Rojo", "Anaranjado", "Verde" }));
        colorfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorfigActionPerformed(evt);
            }
        });

        bordefig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro", "Rojo", "Anaranjado", "Verde" }));
        bordefig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bordefigActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PNG", "JPG" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Fondo Figura");

        jLabel5.setText("Contorno Figura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(fig, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colorfig, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bordefig, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)))
                        .addGap(72, 72, 72)
                        .addComponent(jButton1)
                        .addGap(81, 81, 81)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton2)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colorfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bordefig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(fig, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(404, 404, 404))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void figActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_figActionPerformed
        // TODO add your handling code here:
         figura = fig.getSelectedItem().toString();
        if(figura.equals("Cuadrado")){
            //figure=0;
            lbl_cuadrado.setText("Ingrese el lado del cuadrado");
            txt_cuadrado.setVisible(true);
            lbl_triangulo.setVisible(false);
            txt_triangulo.setVisible(false);          
        }
          if(figura.equals("Circulo")){
            //figure=0;
            lbl_cuadrado.setText("Ingrese Radio");
            txt_cuadrado.setVisible(true);
            lbl_triangulo.setVisible(false);
            txt_triangulo.setVisible(false);
       
        }
          if(figura.equals("Triangulo")){
            //figure=0;
            lbl_triangulo.setVisible(true);
            lbl_cuadrado.setText("Ingrese la base");
            txt_cuadrado.setVisible(true);     
            txt_triangulo.setVisible(true); 
        }
          if(figura.equals("Rectangulo")){
            //figure=0;
            lbl_triangulo.setVisible(true);
            lbl_cuadrado.setText("Ingrese la base");
            txt_cuadrado.setVisible(true);     
            txt_triangulo.setVisible(true); 
        }
        
     
    }//GEN-LAST:event_figActionPerformed

    private void txt_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cuadradoActionPerformed

    private void txt_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_trianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_trianguloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
        switch(figura){
            case "Circulo":
                    FiguraCirculoService circulo = new FiguraCirculoService() ;                
                    circulo.CrearFiguraCirculo(Integer.parseInt(txt_cuadrado.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString());
                    circulo.getdrawFigure(jPanel2.getGraphics());
                    jTextField3.setText(Float.toString(circulo.getPerimetrofiguras()));
                    jTextField4.setText(Float.toString(circulo.getAreafiguras()));
            break;
            case "Cuadrado":
                    FiguraCuadradoService cuadrado = new FiguraCuadradoService();
                    cuadrado.CrearFiguraCuadrado(Integer.parseInt(txt_cuadrado.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString());
                    cuadrado.getdrawFigure(jPanel2.getGraphics());
                    jTextField3.setText(Float.toString(cuadrado.getPerimetrofiguras()));
                    jTextField4.setText(Float.toString(cuadrado.getAreafiguras()));
                   
            break;
            case "Rectangulo":
                   FiguraRectanguloService rectangulo = new FiguraRectanguloService();
                   rectangulo.CrearFiguraRectangulo(Integer.parseInt(txt_cuadrado.getText()),Integer.parseInt(txt_triangulo.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString());
                    rectangulo.getdrawFigure(jPanel2.getGraphics());
                    jTextField3.setText(Float.toString(rectangulo.getPerimetrofiguras()));
                    jTextField4.setText(Float.toString(rectangulo.getAreafiguras()));
                   
            break;
            case "Triangulo":
                 FiguraTrianguloService triangulo = new FiguraTrianguloService();
                   triangulo.CrearFiguraTriangulo(Integer.parseInt(txt_cuadrado.getText()),Integer.parseInt(txt_triangulo.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString());
                    triangulo.getdrawFigure(jPanel2.getGraphics());
                    jTextField3.setText(Float.toString(triangulo.getPerimetrofiguras()));
                    jTextField4.setText(Float.toString(triangulo.getAreafiguras()));
            break;
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      switch(figura){
            case "Circulo":
                    FiguraCirculoService circulo = new FiguraCirculoService() ;                
                    circulo.CrearFiguraCirculo(Integer.parseInt(txt_cuadrado.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString());
                    circulo.getimage(jComboBox1.getSelectedItem().toString());   
            break;
            case "Cuadrado":
                    FiguraCuadradoService cuadrado = new FiguraCuadradoService();              
                    cuadrado.CrearFiguraCuadrado(Integer.parseInt(txt_cuadrado.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString());
                    cuadrado.getimage(jComboBox1.getSelectedItem().toString());   
            break;
            case "Rectangulo":
                FiguraRectanguloService rectangulo = new FiguraRectanguloService();              
                 rectangulo.CrearFiguraRectangulo(Integer.parseInt(txt_cuadrado.getText()),Integer.parseInt(txt_triangulo.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString());
                    rectangulo.getimage(jComboBox1.getSelectedItem().toString()); 
            break;
            case "Triangulo":
                FiguraTrianguloService triangulo = new FiguraTrianguloService();
                 triangulo.CrearFiguraTriangulo(Integer.parseInt(txt_cuadrado.getText()),Integer.parseInt(txt_triangulo.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString());
                    triangulo.getimage(jComboBox1.getSelectedItem().toString()); 
            break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void colorfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorfigActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_colorfigActionPerformed

    private void bordefigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bordefigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bordefigActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bordefig;
    private javax.swing.JComboBox<String> colorfig;
    private javax.swing.JComboBox<String> fig;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbl_cuadrado;
    private javax.swing.JLabel lbl_triangulo;
    private javax.swing.JTextField txt_cuadrado;
    private javax.swing.JTextField txt_triangulo;
    // End of variables declaration//GEN-END:variables
}
